#!/bin/bash

commitRegex='^(UPD-[0-9]:[0-9]+|merge|hotfix)'
if ! grep -qE "$commitRegex" "$1"; then
  echo "Aborting according commit message policy. Please specify project issue UPD-XXXX."
  exit 1
fi
